'use strict';

var mimeTypes = {
  'application/atom+xml': ['atom'],
  'application/epub+zip': ['epub'],
  'application/java-archive': ['jar'],
  'application/java-vm': ['class'],
  'application/javascript': ['js'],
  'application/json': ['json'],
  'application/msword': ['doc', 'dot'],
  'application/pdf': ['pdf'],
  'application/pgp-encrypted': ['pgp'],
  'application/pls+xml': ['pls'],
  'application/postscript': ['ai eps ps'],
  'application/rdf+xml': ['rdf'],
  'application/rss+xml': ['rss'],
  'application/rtf': ['rtf'],
  'application/vnd.adobe.air-application-installer-package+zip': ['air'],
  'application/vnd.android.package-archive': ['apk'],
  'application/vnd.apple.installer+xml': ['mpkg'],
  'application/vnd.apple.mpegurl': ['m3u8'],
  'application/vnd.dart': ['dart'],
  'application/vnd.macports.portpkg': ['portpkg'],
  'application/vnd.mozilla.xul+xml': ['xul'],
  'application/vnd.ms-cab-compressed': ['cab'],
  'application/vnd.ms-excel': ['xls', 'xlm', 'xla', 'xlc', 'xlt', 'xlw'],
  'application/vnd.ms-powerpoint': ['ppt', 'pps', 'pot'],
  'application/vnd.ms-xpsdocument': ['xps'],
  'application/vnd.unity': ['unityweb'],
  'application/vnd.visio': ['vsd', 'vst', 'vss', 'vsw'],
  'application/winhlp': ['hlp'],
  'application/wsdl+xml': ['wsdl'],
  'application/x-7z-compressed': ['7z'],
  'application/x-abiword': ['abw'],
  'application/x-ace-compressed': ['ace'],
  'application/x-apple-diskimage': ['dmg'],
  'application/x-bittorrent': ['torrent'],
  'application/x-bzip': ['bz'],
  'application/x-bzip2': ['bz2', 'boz'],
  'application/x-director': ['dir', 'dcr', 'dxr', 'cst', 'cct', 'cxt', 'w3d', 'fgd', 'swa'],
  'application/x-font-otf': ['otf'],
  'application/x-font-ttf': ['ttf', 'ttc'],
  'application/x-font-type1': ['pfa', 'pfb', 'pfm', 'afm'],
  'application/font-woff': ['woff'],
  'application/x-iso9660-image': ['iso'],
  'application/x-java-jnlp-file': ['jnlp'],
  'application/x-lzh-compressed': ['lzh', 'lha'],
  'application/x-mobipocket-ebook': ['prc', 'mobi'],
  'application/x-msdownload': ['exe', 'dll', 'com', 'bat', 'msi'],
  'application/x-rar-compressed': ['rar'],
  'application/x-shockwave-flash': ['swf'],
  'application/x-silverlight-app': ['xap'],
  'application/x-tar': ['tar'],
  'application/xhtml+xml': ['xhtml', 'xht'],
  'application/xml': ['xml', 'xsl'],
  'application/zip': ['zip'],
  'audio/mp4': ['mp4a'],
  'audio/mpeg': ['mpga', 'mp2', 'mp2a', 'mp3', 'm2a', 'm3a'],
  'audio/ogg': ['oga', 'ogg', 'spx'],
  'audio/x-aac ': ['aac'],
  'audio/x-aiff': ['aif', 'aiff', 'aifc'],
  'audio/x-flac': ['flac'],
  'audio/x-matroska': ['mka'],
  'audio/x-mpegurl': ['m3u'],
  'audio/x-ms-wma': ['wma'],
  'audio/x-wav': ['wav'],
  'image/bmp': ['bmp'],
  'image/gif': ['gif'],
  'image/jpeg': ['jpeg', 'jpg', 'jpe'],
  'image/png': ['png'],
  'image/svg+xml': ['svg', 'svgz'],
  'image/tiff': ['tiff', 'tif'],
  'image/vnd.adobe.photoshop': ['psd'],
  'image/webp': ['webp'],
  'image/x-3ds': ['3ds'],
  'image/x-icon': ['ico'],
  'image/x-rgb': ['rgb'],
  'image/x-tga': ['tga'],
  'image/x-xbitmap': ['xbm'],
  'image/x-xpixmap': ['xpm'],
  'message/rfc822': ['eml', 'mime'],
  'model/iges': ['igs', 'iges'],
  'model/mesh': ['msh', 'mesh', 'silo'],
  'model/vnd.collada+xml': ['dae'],
  'model/vnd.dwf': ['dwf'],
  'model/vnd.gdl': ['gdl'],
  'model/vnd.gtw': ['gtw'],
  'model/vnd.mts': ['mts'],
  'model/vnd.vtu': ['vtu'],
  'model/vrml': ['wrl vrml'],
  'model/x3d+binary': ['x3db', 'x3dbz'],
  'model/x3d+vrml': ['x3dv', 'x3dvz'],
  'model/x3d+xml': ['x3d', 'x3dz'],
  'text/calendar': ['ics', 'ifb'],
  'text/css': ['css'],
  'text/csv': ['csv'],
  'text/html': ['html', 'htm'],
  'text/n3': ['n3'],
  'text/plain': ['txt', 'text', 'conf', 'def', 'list', 'log', 'in'],
  'text/uri-list': ['uri', 'uris', 'urls'],
  'text/vcard': ['vcard'],
  'text/vnd.curl': ['curl'],
  'text/x-c': ['c', 'cc', 'cxx', 'cpp', 'h', 'hh', 'dic'],
  'text/x-java-source': ['java'],
  'text/x-nfo': ['nfo'],
  'text/x-sfv': ['sfv'],
  'text/x-vcalendar': ['vcs'],
  'text/x-vcard': ['vcf'],
  'video/3gpp': ['3gp'],
  'video/h264': ['h264'],
  'video/mp4': ['mp4', 'mp4v', 'mpg4'],
  'video/mpeg': ['mpeg', 'mpg', 'mpe', 'm1v', 'm2v'],
  'video/ogg': ['ogv'],
  'video/quicktime': ['qt', 'mov'],
  'video/webm': ['webm'],
  'video/x-f4v': ['f4v'],
  'video/x-flv': ['flv'],
  'video/x-m4v': ['m4v'],
  'video/x-matroska': ['mkv', 'mk3d', 'mks'],
  'video/x-ms-asf': ['asf asx'],
  'video/x-ms-wmv': ['wmv'],
  'video/x-msvideo': ['avi']
};


module.exports = function (ext) {
  var reg, prop;
  if (!!ext && typeof ext === 'string') {
    for (prop in mimeTypes) {
      if (mimeTypes.hasOwnProperty(prop) && mimeTypes[prop].indexOf(ext) !== -1) {
        return prop;
      }
    }
  }
};
